### ISSUE TITLE
Question: Which is the minimum supported version of QuestPDF?

### ISSUE THREAD

**Issue by TobiasMorell** [VerifyTests/Verify.QuestPDF#188]
#### Is the feature request related to a problem

A clear and concise description of what the problem is.

Using Verify.QuestPDF alongside QuestPDF v. 2022.12.5 yields the following exception at initialization:

> System.TypeLoadException
> Could not load type 'QuestPDF.Infrastructure.DocumentMetadata' from assembly 'QuestPDF, Version=2022.12.5.0, Culture=neutral, PublicKeyToken=null'.

Initialization code:

```cs
public class TestInitializer
{
    [ModuleInitializer]
    public static void InitializeQuestPdfVerifier()
    {
        VerifyQuestPdf.Initialize();
    }
}
```

#### Describe the solution

I'd like the README to state the minimum viable version of QuestPDF that this library is compatible with.

#### Describe alternatives considered

A more descriptive exception message could also be helpful.

**Comment by SimonCropp** [comment]
hmm. i suspect QuestPDF has made some breaking changes and the APIs are now out of sync. 

let me deploy a new verison

**Comment by SimonCropp** [comment]
actually. no thats not it. the current Verify.QuestPDF nuget expects QuestPDF >= 2023.10.0

https://www.nuget.org/packages/Verify.QuestPDF/#dependencies-body-tab

**Comment by TobiasMorell** [comment]
Thanks for the reply. That was exactly what I was hoping to learn.
