### ISSUE TITLE
Verification of images is not cross-platform

### ISSUE THREAD

**Issue by rstm-sf** [VerifyTests/Verify.QuestPDF#6]
#### Describe the bug

Verification of images is not cross-platform.

#### Minimal Repro

https://github.com/rstm-sf/Verify.QuestPDF/pull/1

On latest ubuntu 
```bash
A total of 1 test files matched the specified pattern.
  Failed PagesToInclude [410 ms]
  Error Message:
   VerifyException : Directory: /home/runner/work/Verify.QuestPDF/Verify.QuestPDF/src/Tests
NotEqual:
  - Received: Samples.PagesToInclude.received.png
    Verified: Samples.PagesToInclude.verified.png
Equal:
  - Received: Samples.PagesToInclude.received.txt
    Verified: Samples.PagesToInclude.verified.txt

  Stack Trace:
  Failed PagesToIncludeDynamic [39 ms]
  Error Message:
   VerifyException : Directory: /home/runner/work/Verify.QuestPDF/Verify.QuestPDF/src/Tests
NotEqual:
  - Received: Samples.PagesToIncludeDynamic.received.png
    Verified: Samples.PagesToIncludeDynamic.verified.png
Equal:
  - Received: Samples.PagesToIncludeDynamic.received.txt
    Verified: Samples.PagesToIncludeDynamic.verified.txt

  Stack Trace:
  Failed VerifyDocument [37 ms]
  Error Message:
   VerifyException : Directory: /home/runner/work/Verify.QuestPDF/Verify.QuestPDF/src/Tests
NotEqual:
  - Received: Samples.VerifyDocument#00.received.png
    Verified: Samples.VerifyDocument#00.verified.png
  - Received: Samples.VerifyDocument#01.received.png
    Verified: Samples.VerifyDocument#01.verified.png
Equal:
  - Received: Samples.VerifyDocument.received.txt
    Verified: Samples.VerifyDocument.verified.txt

  Stack Trace:

Failed!  - Failed:     3, Passed:     0, Skipped:     0, Total:     3, Duration: 491 ms - Tests.dll (net7.0)
```

**Comment by SimonCropp** [comment]
try using an image comparer https://github.com/VerifyTests/Verify/blob/main/docs/comparer.md#pre-packaged-comparers

**Comment by rstm-sf** [comment]
Oops, thanks! This work with Verify.ImageHash (haven't tried other) https://github.com/rstm-sf/Verify.QuestPDF/actions/runs/4183426318/jobs/7247767313#step:4:22 

Make a pull request for an example?

But it still seems to me that initially there should be a cross-platform comparison without additional code

**Comment by SimonCropp** [comment]
> But it still seems to me that initially there should be a cross-platform comparison without additional code

i dont think that is possible? Verify.QuestPDF should not ref any comparer project

**Comment by rstm-sf** [comment]
> 

Ok, thanks

**Comment by luis-fss** [comment]
Hi Simon, I am also having this problem.
I tried using the image comparators you suggested, but the results seemed a little inaccurate.
Even deliberately forcing some changes in the reports, the comparators attested that the result was the same, when obviously they were not.
Without the image comparators and in a Windows environment, even a single character is enough to fail the test.
I really need better consistency in testing in Windows and Linux environment.
Can you help me?

**Comment by SimonCropp** [comment]
@luis-fss not much i can do from this side. i suggest you raise it with the QuestPDF project.

**Comment by luis-fss** [comment]
Ok @SimonCropp thanks.
